name: "Skapa release"

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Bygg!
    runs-on: windows-latest
    steps:
    - run: ls
    - run: dotnet build TestRelease.sln --configuration release
