name: "Skapa release"

on:
  release:
    types: [published]

jobs:
  build:
    name: Bygg!
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3.6.0
    - run: echo "${{ github.ref }}"
    - run: dotnet build TestRelease.sln --configuration release
