name: "Skapa release"

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Bygg!
    runs-on: windows-latest
    steps:
    - name: list files
      uses: Rishabh510/Path-lister-action@master
      with:
        path: "."
    - run: dotnet build TestRelease.sln --configuration release
