name: "Skapa release"

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Bygg!
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3.6.0
    - run: dotnet build TestRelease.sln --configuration release
