name: "Skapa release"

on:
  release:
    types: [created]

jobs:
  build:
    name: Bygg!
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3.6.0
    - run: echo "[Release name]: ${{ github.event.release.name }} [Release body]: ${{ github.event.release.body }}"
    - run: dotnet build TestRelease.sln --configuration release
